---
- hosts: all
  gather_facts: false

  tasks:
    - name: Long running task - 1
      ansible.builtin.command: sleep 15
      changed_when: false
      async: 16
      poll: 0 # Fire and Forget 

    - name: Long running task - 1
      ansible.builtin.command: sleep 15
      changed_when: false
      async: 16
      poll: 10

    - name: Long running task - 1
      ansible.builtin.command: sleep 15
      changed_when: false
      async: 16
      poll: 0
