---
- hosts: all
  become: true

  handlers:
    - name: Restart service
      import_tasks: handlers.yaml

  tasks:
    - ansible.builtin.import_tasks: apache2.yaml
      vars:
        state: present
