---
- 
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: "Installing apache2 webserver"
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Copy apache2 configuration file
      ansible.builtin.copy:
        src: apache2.conf
        dest: /etc/apache2/sites-enabled/000-default.conf
      notify: Restart apache2

    - name: Enable the Apache2 module rewrite
      community.general.apache2_module:
        state: present
        name: rewrite
      notify: Restart apache2

    - name: Copy index.html file
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html
        mode: 0664
  
  handlers:
    - name: Restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
