---
- hosts: all
  become: true
  gather_facts: false

  vars_prompt:
    - name: password
      prompt: Enter your password?
      private: true

  tasks:
    - name: Creating user
      ansible.builtin.user:
        name: redwall
        password: "{{ password | hash('blowfish') }}"
        shell: /bin/bash
